services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ruta9
      MYSQL_PASSWORD: ruta9-pwd
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ruta9
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
